//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:NuGetTemplatesPlus.1")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:NuGetTemplatesPlus.1", IsNullable=false)]
public partial class nuGetTemplatesPlus {
    
    private nuGetTemplatesPlusDependency[] dependenciesField;
    
    private nuGetTemplatesPlusSourceFiles sourceFilesField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("dependency", IsNullable=false)]
    public nuGetTemplatesPlusDependency[] dependencies {
        get {
            return this.dependenciesField;
        }
        set {
            this.dependenciesField = value;
        }
    }
    
    /// <remarks/>
    public nuGetTemplatesPlusSourceFiles sourceFiles {
        get {
            return this.sourceFilesField;
        }
        set {
            this.sourceFilesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:NuGetTemplatesPlus.1")]
public partial class nuGetTemplatesPlusDependency {
    
    private string idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:NuGetTemplatesPlus.1")]
public abstract partial class RuleBody {
    
    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("applyCustomTool", typeof(RuleBodyApplyCustomTool))]
    [System.Xml.Serialization.XmlElementAttribute("includeXmlSchema", typeof(RuleBodyIncludeXmlSchema))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:NuGetTemplatesPlus.1")]
public partial class RuleBodyApplyCustomTool {
    
    private string typeField;
    
    private string parameterField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string parameter {
        get {
            return this.parameterField;
        }
        set {
            this.parameterField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:NuGetTemplatesPlus.1")]
public partial class RuleBodyIncludeXmlSchema {
    
    private string fileField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string file {
        get {
            return this.fileField;
        }
        set {
            this.fileField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:NuGetTemplatesPlus.1")]
public partial class nuGetTemplatesPlusSourceFiles {
    
    private RuleBody[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ifCustomCondition", typeof(nuGetTemplatesPlusSourceFilesIfCustomCondition))]
    [System.Xml.Serialization.XmlElementAttribute("ifFileExtension", typeof(nuGetTemplatesPlusSourceFilesIfFileExtension))]
    public RuleBody[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:NuGetTemplatesPlus.1")]
public partial class nuGetTemplatesPlusSourceFilesIfCustomCondition : RuleBody {
    
    private string typeField;
    
    private string parameterField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string parameter {
        get {
            return this.parameterField;
        }
        set {
            this.parameterField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:NuGetTemplatesPlus.1")]
public partial class nuGetTemplatesPlusSourceFilesIfFileExtension : RuleBody {
    
    private string extensionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string extension {
        get {
            return this.extensionField;
        }
        set {
            this.extensionField = value;
        }
    }
}
